--
-- PostgreSQL database dump
--

-- Dumped from database version 16.3
-- Dumped by pg_dump version 16.3

-- Started on 2024-07-09 01:45:57

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 241 (class 1259 OID 16830)
-- Name: AboutUs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AboutUs" (
    "Id" integer NOT NULL,
    "Title" character varying(100) NOT NULL,
    "Slug" character varying(100) NOT NULL,
    "Description" text NOT NULL
);


ALTER TABLE public."AboutUs" OWNER TO postgres;

--
-- TOC entry 240 (class 1259 OID 16829)
-- Name: AboutUs_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."AboutUs" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AboutUs_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 16754)
-- Name: BidValues; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."BidValues" (
    "Id" integer NOT NULL,
    "Value" integer NOT NULL
);


ALTER TABLE public."BidValues" OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 16753)
-- Name: BidValues_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."BidValues" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."BidValues_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 235 (class 1259 OID 16806)
-- Name: ContactUs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."ContactUs" (
    "Id" integer NOT NULL,
    "PrimaryTollFreeNumber" text NOT NULL,
    "PrimaryEmail" text NOT NULL,
    "SecondaryTollFreeNumber" text NOT NULL,
    "SecondaryEmail" text NOT NULL,
    "Address" text NOT NULL
);


ALTER TABLE public."ContactUs" OWNER TO postgres;

--
-- TOC entry 234 (class 1259 OID 16805)
-- Name: ContactUs_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."ContactUs" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ContactUs_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 231 (class 1259 OID 16790)
-- Name: GameConfigs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."GameConfigs" (
    "Id" integer NOT NULL,
    "AdminCommission" integer NOT NULL,
    "SignupBonus" integer NOT NULL,
    "SupportMail" text NOT NULL,
    "WhatsappLink" text NOT NULL,
    "YoutubeLink" text NOT NULL,
    "ApiKey" text NOT NULL,
    "SecretKey" text NOT NULL
);


ALTER TABLE public."GameConfigs" OWNER TO postgres;

--
-- TOC entry 230 (class 1259 OID 16789)
-- Name: GameConfigs_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."GameConfigs" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."GameConfigs_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 227 (class 1259 OID 16774)
-- Name: GeneralSettings; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."GeneralSettings" (
    "Id" integer NOT NULL,
    "WebsiteName" text NOT NULL,
    "WebsiteURL" text NOT NULL,
    "WebsiteTagline" text NOT NULL,
    "WebsiteKeyword" text NOT NULL,
    "WebsiteDescription" text NOT NULL,
    "FooterCopyright" text NOT NULL
);


ALTER TABLE public."GeneralSettings" OWNER TO postgres;

--
-- TOC entry 226 (class 1259 OID 16773)
-- Name: GeneralSettings_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."GeneralSettings" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."GeneralSettings_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 229 (class 1259 OID 16782)
-- Name: LogoSettings; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."LogoSettings" (
    "Id" integer NOT NULL,
    "HeaderLogo" text NOT NULL,
    "FooterLogo" text NOT NULL,
    "Favicon" text NOT NULL
);


ALTER TABLE public."LogoSettings" OWNER TO postgres;

--
-- TOC entry 228 (class 1259 OID 16781)
-- Name: LogoSettings_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."LogoSettings" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."LogoSettings_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 225 (class 1259 OID 16760)
-- Name: ShopCoins; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."ShopCoins" (
    "Id" integer NOT NULL,
    "Value" integer NOT NULL
);


ALTER TABLE public."ShopCoins" OWNER TO postgres;

--
-- TOC entry 224 (class 1259 OID 16759)
-- Name: ShopCoins_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."ShopCoins" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ShopCoins_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 233 (class 1259 OID 16798)
-- Name: SocialMedias; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."SocialMedias" (
    "Id" integer NOT NULL,
    "Facebook" text NOT NULL,
    "Twitter" text NOT NULL,
    "LinkedIn" text NOT NULL,
    "Instagram" text NOT NULL,
    "YouTube" text NOT NULL,
    "WhatsApp" text NOT NULL,
    "Pinterest" text NOT NULL,
    "GitHub" text NOT NULL
);


ALTER TABLE public."SocialMedias" OWNER TO postgres;

--
-- TOC entry 232 (class 1259 OID 16797)
-- Name: SocialMedias_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."SocialMedias" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."SocialMedias_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 237 (class 1259 OID 16814)
-- Name: TermsAndConditions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."TermsAndConditions" (
    "Id" integer NOT NULL,
    "Title" character varying(100) NOT NULL,
    "Slug" character varying(100) NOT NULL,
    "Description" text NOT NULL
);


ALTER TABLE public."TermsAndConditions" OWNER TO postgres;

--
-- TOC entry 236 (class 1259 OID 16813)
-- Name: TermsAndConditions_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."TermsAndConditions" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."TermsAndConditions_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 16729)
-- Name: Transactions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Transactions" (
    "OrderId" integer NOT NULL,
    "PlayerId" integer NOT NULL,
    "TxnId" text NOT NULL,
    "Amount" numeric NOT NULL,
    "Status" text NOT NULL,
    "TransactionDate" timestamp with time zone NOT NULL
);


ALTER TABLE public."Transactions" OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 16728)
-- Name: Transactions_OrderId_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Transactions" ALTER COLUMN "OrderId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Transactions_OrderId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 217 (class 1259 OID 16696)
-- Name: Users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Users" (
    "Id" integer NOT NULL,
    "Name" text NOT NULL,
    "Email" text NOT NULL,
    "WalletAmount" numeric NOT NULL,
    "WinAmount" numeric NOT NULL
);


ALTER TABLE public."Users" OWNER TO postgres;

--
-- TOC entry 216 (class 1259 OID 16695)
-- Name: Users_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Users" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Users_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 219 (class 1259 OID 16704)
-- Name: WithdrawRequests; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."WithdrawRequests" (
    "RequestId" integer NOT NULL,
    "PlayerId" integer NOT NULL,
    "PaymentMethod" character varying(50) NOT NULL,
    "Account" character varying(100) NOT NULL,
    "Status" character varying(20) NOT NULL,
    "Amount" numeric NOT NULL
);


ALTER TABLE public."WithdrawRequests" OWNER TO postgres;

--
-- TOC entry 218 (class 1259 OID 16703)
-- Name: WithdrawRequests_RequestId_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."WithdrawRequests" ALTER COLUMN "RequestId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."WithdrawRequests_RequestId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 215 (class 1259 OID 16690)
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- TOC entry 239 (class 1259 OID 16822)
-- Name: privacyPolicies; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."privacyPolicies" (
    "Id" integer NOT NULL,
    "Title" character varying(100) NOT NULL,
    "Slug" character varying(100) NOT NULL,
    "Description" text NOT NULL
);


ALTER TABLE public."privacyPolicies" OWNER TO postgres;

--
-- TOC entry 238 (class 1259 OID 16821)
-- Name: privacyPolicies_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."privacyPolicies" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."privacyPolicies_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4949 (class 0 OID 16830)
-- Dependencies: 241
-- Data for Name: AboutUs; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."AboutUs" ("Id", "Title", "Slug", "Description") FROM stdin;
1	About Us	about us\n	About Us
\.


--
-- TOC entry 4931 (class 0 OID 16754)
-- Dependencies: 223
-- Data for Name: BidValues; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."BidValues" ("Id", "Value") FROM stdin;
1	80
2	120
\.


--
-- TOC entry 4943 (class 0 OID 16806)
-- Dependencies: 235
-- Data for Name: ContactUs; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."ContactUs" ("Id", "PrimaryTollFreeNumber", "PrimaryEmail", "SecondaryTollFreeNumber", "SecondaryEmail", "Address") FROM stdin;
1	93725564788	ludosikandar_primary@gmail.com	9327654755	ludosikandar_secondary@gmail.com	loremipsumdolorgehen54
\.


--
-- TOC entry 4939 (class 0 OID 16790)
-- Dependencies: 231
-- Data for Name: GameConfigs; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."GameConfigs" ("Id", "AdminCommission", "SignupBonus", "SupportMail", "WhatsappLink", "YoutubeLink", "ApiKey", "SecretKey") FROM stdin;
1	20	500	ludosikandar@gmail.com	Lorem Ipsum Dolor	https://www.youtube.com/watch?v=pPw-EMjLFBI	Lorem Ipsum Dolor	Lorem Ipsum Dolor
\.


--
-- TOC entry 4935 (class 0 OID 16774)
-- Dependencies: 227
-- Data for Name: GeneralSettings; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."GeneralSettings" ("Id", "WebsiteName", "WebsiteURL", "WebsiteTagline", "WebsiteKeyword", "WebsiteDescription", "FooterCopyright") FROM stdin;
1	Ludo Sikandar	https://ludosikandar.com	lorem ipsum dolor	lorem ipsum dolor	lorem ipsum dolor	lorem ipsum dolor
\.


--
-- TOC entry 4937 (class 0 OID 16782)
-- Dependencies: 229
-- Data for Name: LogoSettings; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."LogoSettings" ("Id", "HeaderLogo", "FooterLogo", "Favicon") FROM stdin;
\.


--
-- TOC entry 4933 (class 0 OID 16760)
-- Dependencies: 225
-- Data for Name: ShopCoins; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."ShopCoins" ("Id", "Value") FROM stdin;
1	20
2	40
3	50
\.


--
-- TOC entry 4941 (class 0 OID 16798)
-- Dependencies: 233
-- Data for Name: SocialMedias; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."SocialMedias" ("Id", "Facebook", "Twitter", "LinkedIn", "Instagram", "YouTube", "WhatsApp", "Pinterest", "GitHub") FROM stdin;
1	http://localhost:5299/SocialMedia	http://localhost:5299/SocialMedia	http://localhost:5299/SocialMedia	http://localhost:5299/SocialMedia	http://localhost:5299/SocialMedia	http://localhost:5299/SocialMedia	http://localhost:5299/SocialMedia	http://localhost:5299/SocialMedia
\.


--
-- TOC entry 4945 (class 0 OID 16814)
-- Dependencies: 237
-- Data for Name: TermsAndConditions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."TermsAndConditions" ("Id", "Title", "Slug", "Description") FROM stdin;
1	T&C01	T&C01	T&C01
\.


--
-- TOC entry 4929 (class 0 OID 16729)
-- Dependencies: 221
-- Data for Name: Transactions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Transactions" ("OrderId", "PlayerId", "TxnId", "Amount", "Status", "TransactionDate") FROM stdin;
1	1	101121	250.00	approved	2024-06-30 22:14:09.926+05:30
\.


--
-- TOC entry 4925 (class 0 OID 16696)
-- Dependencies: 217
-- Data for Name: Users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Users" ("Id", "Name", "Email", "WalletAmount", "WinAmount") FROM stdin;
1	testuser_01	testuser_01@gmail.com	1000.00	10.00
2	testuser_02	testuser_02@gmail.com	250.00	12.00
3	testuser_03	testuser_03@gmail.com	5125.00	75.00
4	testuser_04	testuser_04@gmail.com	2300.00	18.00
\.


--
-- TOC entry 4927 (class 0 OID 16704)
-- Dependencies: 219
-- Data for Name: WithdrawRequests; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."WithdrawRequests" ("RequestId", "PlayerId", "PaymentMethod", "Account", "Status", "Amount") FROM stdin;
1	1	UPI	0669104000222259	pending	250.00
\.


--
-- TOC entry 4923 (class 0 OID 16690)
-- Dependencies: 215
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20240626213823_InitialCreate	8.0.6
20240630120157_AddWithdrawRequest	8.0.6
20240630151517_CreateTransaction	8.0.6
20240630152806_CreateTransaction	8.0.6
20240630155918_CreateTransaction	8.0.6
20240630170157_AddShopCoins	8.0.6
20240630173141_AddShopCoins	8.0.6
20240630200336_AddBidValue	8.0.6
20240630202326_AddShopCoins	8.0.6
20240702103415_AddGeneralSettings	8.0.6
20240702212807_AddGeneralSettings	8.0.6
20240702224620_AddLogoSettings	8.0.6
20240705204154_AddGameConfig	8.0.6
20240705211203_AddSocialMedia	8.0.6
20240706052551_AddContactUs	8.0.6
20240706080140_AddTermsAndConditions	8.0.6
20240706094659_AddPrivacyPolicies	8.0.6
20240706101345_AddAboutUs	8.0.6
20240707104209_AddApplicationUser	8.0.6
20240707111125_CreateIdentitySchema	8.0.6
\.


--
-- TOC entry 4947 (class 0 OID 16822)
-- Dependencies: 239
-- Data for Name: privacyPolicies; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."privacyPolicies" ("Id", "Title", "Slug", "Description") FROM stdin;
1	privacy policy 1	privacy policy 1	privacy policy 1\n
\.


--
-- TOC entry 4955 (class 0 OID 0)
-- Dependencies: 240
-- Name: AboutUs_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."AboutUs_Id_seq"', 1, true);


--
-- TOC entry 4956 (class 0 OID 0)
-- Dependencies: 222
-- Name: BidValues_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."BidValues_Id_seq"', 8, true);


--
-- TOC entry 4957 (class 0 OID 0)
-- Dependencies: 234
-- Name: ContactUs_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."ContactUs_Id_seq"', 1, true);


--
-- TOC entry 4958 (class 0 OID 0)
-- Dependencies: 230
-- Name: GameConfigs_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."GameConfigs_Id_seq"', 1, true);


--
-- TOC entry 4959 (class 0 OID 0)
-- Dependencies: 226
-- Name: GeneralSettings_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."GeneralSettings_Id_seq"', 1, true);


--
-- TOC entry 4960 (class 0 OID 0)
-- Dependencies: 228
-- Name: LogoSettings_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."LogoSettings_Id_seq"', 2, true);


--
-- TOC entry 4961 (class 0 OID 0)
-- Dependencies: 224
-- Name: ShopCoins_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."ShopCoins_Id_seq"', 3, true);


--
-- TOC entry 4962 (class 0 OID 0)
-- Dependencies: 232
-- Name: SocialMedias_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."SocialMedias_Id_seq"', 1, true);


--
-- TOC entry 4963 (class 0 OID 0)
-- Dependencies: 236
-- Name: TermsAndConditions_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."TermsAndConditions_Id_seq"', 4, true);


--
-- TOC entry 4964 (class 0 OID 0)
-- Dependencies: 220
-- Name: Transactions_OrderId_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Transactions_OrderId_seq"', 3, true);


--
-- TOC entry 4965 (class 0 OID 0)
-- Dependencies: 216
-- Name: Users_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Users_Id_seq"', 4, true);


--
-- TOC entry 4966 (class 0 OID 0)
-- Dependencies: 218
-- Name: WithdrawRequests_RequestId_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."WithdrawRequests_RequestId_seq"', 2, true);


--
-- TOC entry 4967 (class 0 OID 0)
-- Dependencies: 238
-- Name: privacyPolicies_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."privacyPolicies_Id_seq"', 1, true);


--
-- TOC entry 4779 (class 2606 OID 16836)
-- Name: AboutUs PK_AboutUs; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AboutUs"
    ADD CONSTRAINT "PK_AboutUs" PRIMARY KEY ("Id");


--
-- TOC entry 4761 (class 2606 OID 16758)
-- Name: BidValues PK_BidValues; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."BidValues"
    ADD CONSTRAINT "PK_BidValues" PRIMARY KEY ("Id");


--
-- TOC entry 4773 (class 2606 OID 16812)
-- Name: ContactUs PK_ContactUs; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ContactUs"
    ADD CONSTRAINT "PK_ContactUs" PRIMARY KEY ("Id");


--
-- TOC entry 4769 (class 2606 OID 16796)
-- Name: GameConfigs PK_GameConfigs; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."GameConfigs"
    ADD CONSTRAINT "PK_GameConfigs" PRIMARY KEY ("Id");


--
-- TOC entry 4765 (class 2606 OID 16780)
-- Name: GeneralSettings PK_GeneralSettings; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."GeneralSettings"
    ADD CONSTRAINT "PK_GeneralSettings" PRIMARY KEY ("Id");


--
-- TOC entry 4767 (class 2606 OID 16788)
-- Name: LogoSettings PK_LogoSettings; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."LogoSettings"
    ADD CONSTRAINT "PK_LogoSettings" PRIMARY KEY ("Id");


--
-- TOC entry 4763 (class 2606 OID 16764)
-- Name: ShopCoins PK_ShopCoins; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ShopCoins"
    ADD CONSTRAINT "PK_ShopCoins" PRIMARY KEY ("Id");


--
-- TOC entry 4771 (class 2606 OID 16804)
-- Name: SocialMedias PK_SocialMedias; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."SocialMedias"
    ADD CONSTRAINT "PK_SocialMedias" PRIMARY KEY ("Id");


--
-- TOC entry 4775 (class 2606 OID 16820)
-- Name: TermsAndConditions PK_TermsAndConditions; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TermsAndConditions"
    ADD CONSTRAINT "PK_TermsAndConditions" PRIMARY KEY ("Id");


--
-- TOC entry 4759 (class 2606 OID 16735)
-- Name: Transactions PK_Transactions; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Transactions"
    ADD CONSTRAINT "PK_Transactions" PRIMARY KEY ("OrderId");


--
-- TOC entry 4755 (class 2606 OID 16702)
-- Name: Users PK_Users; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT "PK_Users" PRIMARY KEY ("Id");


--
-- TOC entry 4757 (class 2606 OID 16710)
-- Name: WithdrawRequests PK_WithdrawRequests; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."WithdrawRequests"
    ADD CONSTRAINT "PK_WithdrawRequests" PRIMARY KEY ("RequestId");


--
-- TOC entry 4753 (class 2606 OID 16694)
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- TOC entry 4777 (class 2606 OID 16828)
-- Name: privacyPolicies PK_privacyPolicies; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."privacyPolicies"
    ADD CONSTRAINT "PK_privacyPolicies" PRIMARY KEY ("Id");


-- Completed on 2024-07-09 01:45:58

--
-- PostgreSQL database dump complete
--

